# Change these first
owner: Premium-Fast-Network # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: PFN Website
    url: https://premiumfast.net
  - name: PFN Billing
    url: https://manage.premiumfast.net
  - name: PFN Documentation
    url: https://docs.premiumfast.net
  - name: PFN Panel VPS
    url: https://panel.premiumfast.net:4083
  - name: PFN Panel VPS EU
    url: https://panel-eu.premiumfast.net:4083
    
  - name: KVM VPS SG02-NVMe
    url: $PFN_VSG02
    port: $KVM_VPS_PORT
    check: "tcp-ping"
  - name: KVM VPS SG03-NVMe
    url: $PFN_VSG03
    port: $KVM_VPS_PORT
    check: "tcp-ping"
  - name: KVM VPS DE01-NVMe
    url: $PFN_VDE01
    port: $KVM_VPS_PORT
    check: "tcp-ping"
  - name: KVM VPS DE02-NVMe
    url: $PFN_VDE02
    port: $KVM_VPS_PORT
    check: "tcp-ping"
  - name: KVM VPS DE03-NVMe
    url: $PFN_VDE03
    port: $KVM_VPS_PORT
    check: "tcp-ping"
    
  - name: GRE-DE03
    url: $PFN_GREDE03
    port: 22
    check: "tcp-ping"
    
  - name: PFN Seedbox01
    url: https://s01.pfnservers.net
    expectedStatusCodes:
      - 200
      - 401
  - name: PFN Seedbox02
    url: https://s02.pfnservers.net
    expectedStatusCodes:
      - 200
      - 401
      
  - name: PFN VPN US
    url: $PFN_VPNUS
    check: "tcp-ping"
  - name: PFN VPN ID
    url: $PFN_VPNID
    check: "tcp-ping"
  - name: PFN VPN SG
    url: $PFN_VPNSG
    check: "tcp-ping"

  - name: PFNDrive
    url: https://pfndrive.my.id
  - name: PFNDrive API
    url: https://api.pfndrive.my.id
  - name: PFNDrive Console [DEV]
    url: https://console-dev.pfndrive.my.id
  - name: PFNDrive API [DEV]
    url: https://api-dev.pfn.my.id
    
  - name: KrmPesan REG-01
    url: https://region01.krmpesan.com
  - name: KrmPesan REG-02
    url: https://region02.krmpesan.com
  - name: KrmPesan VM-01
    url: $KRMPESAN_VM01
    check: "tcp-ping"
  - name: KrmPesan VM-02
    url: $KRMPESAN_VM02
    check: "tcp-ping"
  - name: KrmPesan VM-03
    url: $KRMPESAN_VM03
    check: "tcp-ping"
  - name: KrmPesan CORE-01
    url: $KRMPESAN_CORE01
    check: "tcp-ping"
  - name: KrmPesan CORE-02
    url: $KRMPESAN_CORE02
    check: "tcp-ping"
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.premiumfast.net
  # baseUrl: /your-repo-name
  logoUrl: /assets/logo.png
  name: PFN Status
  introTitle: "**PFN Status Pages** For Monitoring Server and Website."
  navbar:
    - title: Home
      href: /
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
