# Change these first
owner: Premium-Fast-Network # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: PFN
    url: https://premiumfast.net
  - name: Billing
    url: https://manage.premiumfast.net
  - name: Panel VPS
    url: https://panel.premiumfast.net:4083
  - name: Seedbox01
    url: https://s01.pfnservers.net
  - name: Seedbox02
    url: https://s02.pfnservers.net
  - name: PFNDrive
    url: https://pfndrive.my.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.premiumfast.net
  # baseUrl: /your-repo-name
  logoUrl: https://premiumfast.net/favicon.png
  name: PFN Status
  introTitle: "**PFN Status Pages** For Monitoring Server and Website."
  navbar:
    - title: Home
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
